# GitHub Actions Vue Demo
name: Vue App Build and Deploy # 名称
on:
  push:
    branches:
      - master # master 分支发生push事件时触发
jobs:
  build-and-deploy: # 任务
    runs-on: ubuntu-latest # 运行环境
    steps: # 运行步骤
      - name: Checkout
        uses: actions/checkout@master # 获取源码

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Webhook
        uses: distributhor/workflow-webhook
        with:
          url: "http://amberisgreat.ngrok.io/api/test_pedant"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
